language:
  node_js
node_js:
  - 10
  - 8
install:
  - npm install
  - lerna bootstrap --ci
  - npm install -g codecov
script:
  - npm test
  - lerna run build
  - npm run build:demo
after_success:
  - codecov
