language: node_js
node_js:
  - 10
  - 8
notifications:
  email: false
before_install:
  - npm i -g npm@latest
install:
  - npm ci
  - lerna bootstrap --ci
before_script:
  - npm install -g codecov
script:
  - npm test
  - lerna run build
  - npm run build:demo
after_success:
  - codecov
